#!/bin/bash
# Quick migration checklist for new laptop setup

echo "🚀 NEW LAPTOP MIGRATION CHECKLIST"
echo "================================="
echo ""
echo "□ 1. Install Xcode Command Line Tools"
echo "     xcode-select --install"
echo ""
echo "□ 2. Install Homebrew"
echo "     /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "□ 3. Clone dotfiles"
echo "     git clone https://github.com/kaovilai/dotfiles.git ~/git/dotfiles"
echo ""
echo "□ 4. Run automated migration"
echo "     source ~/git/dotfiles/zsh/functions/migrate-laptop.zsh"
echo "     migrate-to-new-laptop"
echo ""
echo "□ 5. Install from Brewfile"
echo "     brew bundle --file=~/git/dotfiles/Brewfile"
echo ""
echo "□ 6. Export WiFi networks from old laptop"
echo "     export-wifi-credentials"
echo ""
echo "□ 7. Copy SSH keys from old laptop or generate new"
echo "     ssh-keygen -t ed25519 -C \"your-email@example.com\""
echo ""
echo "□ 8. Copy GPG keys from old laptop"
echo "     See: ~/git/dotfiles/docs/LAPTOP_MIGRATION.md"
echo ""
echo "□ 9. Create ~/secrets.zsh with your secrets"
echo ""
echo "□ 10. Configure cloud CLIs"
echo "     aws configure"
echo "     gcloud auth login"
echo "     ibmcloud login"
echo ""
echo "□ 11. Verify setup"
echo "      verify-migration"
echo ""
echo "Press any key to start..."
read -n 1