# Run from the local origin/dev checkout, not the published (upstream) package.
# alias copilot-api="npx @jeffreycao/copilot-api@latest start --claude-code"   # upstream/published, disabled
alias copilot-api="NODE_USE_SYSTEM_CA=1 bun run --cwd \$HOME/git/copilot-api ./src/main.ts start --claude-code"

# Claude Code via GitHub Copilot (copilot-api gateway)
#
# claude-copilot replicates the env command generated by
# `copilot-api start --claude-code` (https://github.com/kaovilai/copilot-api),
# including two not-yet-merged fixes:
#   PR #1 (kaovilai/copilot-api#1): CLAUDE_CODE_USE_VERTEX=0 and
#       CLAUDE_CODE_USE_BEDROCK=0 so an environment already configured for
#       Vertex AI/Bedrock routes to the gateway instead of erroring 403.
#   PR #2 (kaovilai/copilot-api#2): latest available model auto-selected per
#       family; ANTHROPIC_MODEL defaults to Sonnet, falling back to Opus.
#       Of the per-tier ANTHROPIC_DEFAULT_{OPUS,SONNET,HAIKU}_MODEL exports
#       PR #2 generates, only Sonnet is kept here (pinned to the gateway's 1M
#       id); Opus/Haiku are unset so the CLI picks its own — see the block in
#       claude-copilot() below.
# The gateway server itself runs from the local ~/git/copilot-api checkout
# (origin/dev fork), not the published npm package — see the runner block in
# claude-copilot() below. Set COPILOT_API_DIR to point elsewhere, or unset/
# rmdir that path to fall back to the commented-out bunx/npx upstream lines.
#
# By default, claude-copilot sets DISABLE_NON_ESSENTIAL_MODEL_CALLS=1 and
# CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 to cut nonessential
# traffic/telemetry through the gateway. Tradeoff: this also disables Claude
# Code's Monitor tool (https://code.claude.com/docs/en/tools-reference#monitor-tool),
# which breaks anything relying on it (e.g. inter-session plugin's push-based
# messaging). Set CLAUDE_COPILOT_ENABLE_MONITOR=1 to opt back into Monitor
# (e.g. `CLAUDE_COPILOT_ENABLE_MONITOR=1 claude-copilot` or `cec`).
#
# Also defines claude-vertex (raw claude binary routed through Google Vertex
# AI, using CLOUD_ML_REGION/ANTHROPIC_VERTEX_PROJECT_ID already exported in
# the shell — same vars used by computer-use-claude/cecon elsewhere in this
# repo), plus the mode-dispatching `claude` function and the `claude-mode`
# switcher (copilot ↔ vertex, vertex is default) — see bottom of file.

# Highest-versioned Claude model for a family from /v1/models JSON.
# Mirrors PR #2's getLatestModelForFamily: numeric major-then-minor compare,
# handles claude-opus-4.8, claude-opus-4-5-20251101, claude-3-opus-... forms.
# Outputs .claude_model_id (falls back to .id) so the 1M-context variant
# (e.g. "claude-sonnet-5[1m]") is preferred over the plain default-context id
# when the gateway advertises one for that model.
_claude_copilot_latest_model() {
    local family="$1" models_json="$2"
    jq -r --arg fam "$family" '
        [(.data // [])[]
         | select(((.id? // empty) | strings) as $i
                  | ($i | test("claude"; "i")) and ($i | test($fam; "i")))]
        | map({out: (.claude_model_id? // .id),
               v: ((try (.id | capture("(?<maj>[0-9]+)(?:[.-](?<min>[0-9]+))?")) catch null) as $m
                   | if $m == null then 0
                     else (($m.maj | tonumber) * 1000) + (($m.min // "0") | tonumber)
                     end)})
        | sort_by(.v) | last // {} | .out // empty
    ' <<< "$models_json"
}

# Names only (no values) — used to clean up when switching to `vertex` mode
# so gateway config doesn't leak across.
typeset -ga _claude_copilot_env_names=(
    ANTHROPIC_BASE_URL
    ANTHROPIC_AUTH_TOKEN
    ANTHROPIC_MODEL
    ANTHROPIC_DEFAULT_OPUS_MODEL
    ANTHROPIC_DEFAULT_SONNET_MODEL
    ANTHROPIC_DEFAULT_HAIKU_MODEL
    CLAUDE_CODE_USE_VERTEX
    CLAUDE_CODE_USE_BEDROCK
    DISABLE_NON_ESSENTIAL_MODEL_CALLS
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
    CLAUDE_CODE_ATTRIBUTION_HEADER
    CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION
    CLAUDE_CODE_DISABLE_TERMINAL_TITLE
    CLAUDE_CODE_ENABLE_AWAY_SUMMARY
)

_claude_copilot_unset_env() {
    unset "${_claude_copilot_env_names[@]}"
}

claude-copilot() {
    if ! command -v jq &>/dev/null; then
        echo "❌ jq not found. Install it with: brew install jq" >&2
        return 1
    fi

    local port="${COPILOT_API_PORT:-4141}"
    local base="http://localhost:${port}"
    local log="${TMPDIR:-/tmp}/copilot-api-${port}.log"

    # Start the gateway if nothing is serving yet
    if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
        local -a runner
        local repo_dir="${COPILOT_API_DIR:-$HOME/git/copilot-api}"
        if [[ -d "$repo_dir/.git" ]] && command -v bun &>/dev/null; then
            # Local origin/dev checkout — bun runs the TS source directly, so
            # uncommitted work-in-progress fixes are picked up with no build step.
            runner=(env NODE_USE_SYSTEM_CA=1 bun run --cwd "$repo_dir" ./src/main.ts)
        elif command -v bunx &>/dev/null; then
            # upstream/published fallback, disabled by default (see above)
            # runner=(bunx copilot-api@latest)
            echo "❌ Local checkout not found at ${repo_dir}. Set COPILOT_API_DIR or uncomment the bunx/npx fallback." >&2
            return 1
        elif command -v npx &>/dev/null; then
            # runner=(npx -y copilot-api@latest)
            echo "❌ Local checkout not found at ${repo_dir}. Set COPILOT_API_DIR or uncomment the bunx/npx fallback." >&2
            return 1
        else
            echo "❌ Need bunx or npx to run copilot-api. Install bun or node." >&2
            return 1
        fi
        echo "Starting copilot-api on ${base} (log: ${log})..."
        ("${runner[@]}" start --port "${port}" >> "${log}" 2>&1 &)
        local i
        for i in {1..60}; do
            curl -sf --max-time 2 "${base}/v1/models" -o /dev/null && break
            sleep 1
        done
        if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
            echo "❌ copilot-api not ready on ${base} after 60s." >&2
            echo "   First run needs GitHub device auth: tail -f ${log}" >&2
            echo "   Or run interactively once: ${runner[*]} start --port ${port}" >&2
            return 1
        fi
    fi

    local models_json
    models_json=$(curl -sf --max-time 10 "${base}/v1/models") || {
        echo "❌ Failed to fetch ${base}/v1/models" >&2
        return 1
    }

    local opus sonnet haiku
    opus=$(_claude_copilot_latest_model opus "$models_json")
    sonnet=$(_claude_copilot_latest_model sonnet "$models_json")
    haiku=$(_claude_copilot_latest_model haiku "$models_json")

    local main_model="${sonnet:-$opus}"
    if [[ -z "$main_model" ]]; then
        echo "❌ No Claude models available from ${base}/v1/models" >&2
        return 1
    fi

    echo "claude-copilot → opus: ${opus:-n/a}, sonnet: ${sonnet:-n/a}, haiku: ${haiku:-n/a}"

    # Env block mirrors the --claude-code generated command + PR #1/#2 fixes.
    local -a envs
    envs=(
        ANTHROPIC_BASE_URL="${base}"
        ANTHROPIC_AUTH_TOKEN="dummy"
        ANTHROPIC_MODEL="${main_model}"
        CLAUDE_CODE_USE_VERTEX=0
        CLAUDE_CODE_USE_BEDROCK=0
        CLAUDE_CODE_ATTRIBUTION_HEADER=0
        CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION=false
        CLAUDE_CODE_DISABLE_TERMINAL_TITLE=true
        CLAUDE_CODE_ENABLE_AWAY_SUMMARY=0
    )
    if [[ -z "$CLAUDE_COPILOT_ENABLE_MONITOR" || "$CLAUDE_COPILOT_ENABLE_MONITOR" == 0 ]]; then
        envs+=(
            DISABLE_NON_ESSENTIAL_MODEL_CALLS=1
            CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
        )
    fi
    # Opus/Haiku tier defaults are deliberately NOT exported (diverging from
    # PR #2), so the CLI's own built-in defaults apply and stay current as
    # Claude Code ships newer models. They are unset rather than merely omitted
    # because the shell may already export them for Vertex (see secrets.zsh) —
    # a stale pin there would otherwise leak into gateway mode and pick an
    # older model than the gateway offers.
    unset ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
    # Sonnet is the exception: pin it to the gateway's detected id so the 1M-
    # context variant (claude-sonnet-5[1m]) is used rather than the CLI's
    # default-context Sonnet.
    if [[ -n "$sonnet" ]]; then
        envs+=(ANTHROPIC_DEFAULT_SONNET_MODEL="${sonnet}")
    else
        unset ANTHROPIC_DEFAULT_SONNET_MODEL
    fi

    # `export` writes into the calling shell (not a subprocess-only scope) so
    # any later child process — including Claude Code re-entering an agent
    # shell via the left-arrow session view — inherits the gateway config
    # instead of falling back to default subscription auth.
    # `command` bypasses the claude() shell function without exec'ing a new
    # process (unlike env), avoiding claude() → claude-copilot → claude()
    # recursion while keeping the exported vars in this same shell.
    export "${envs[@]}"
    command claude "$@"
}

# copilot-api-kill: stop the detached gateway process started by
# claude-copilot. There's no saved PID (it's launched via `(... &)` in a
# subshell), so this finds whatever's listening on COPILOT_API_PORT
# (default 4141) and kills it, escalating to SIGKILL if it won't die.
copilot-api-kill() {
    local port="${COPILOT_API_PORT:-4141}"
    local -a pids
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -z "${pids[1]}" ]]; then
        echo "No process listening on port ${port}."
        return 1
    fi
    echo "Killing copilot-api on port ${port} (pid: ${pids[*]})..."
    kill "${pids[@]}" 2>/dev/null
    sleep 1
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -n "${pids[1]}" ]]; then
        echo "Still alive, sending SIGKILL..."
        kill -9 "${pids[@]}" 2>/dev/null
    fi
}

# ---------------------------------------------------------------------------
# claude-vertex: raw claude binary, routed through Google Vertex AI. Unlike
# claude-copilot, no local gateway process is needed — Claude Code talks to
# Vertex directly once CLAUDE_CODE_USE_VERTEX is set. Requires
# CLOUD_ML_REGION and ANTHROPIC_VERTEX_PROJECT_ID already exported in the
# shell (same vars computer-use-claude/cecon/claude-container use elsewhere
# in this repo) and gcloud ADC set up (`gcloud auth application-default
# login`).
claude-vertex() {
    if [[ -z "$CLOUD_ML_REGION" || -z "$ANTHROPIC_VERTEX_PROJECT_ID" ]]; then
        echo "❌ CLOUD_ML_REGION and ANTHROPIC_VERTEX_PROJECT_ID must be exported to use Vertex AI." >&2
        return 1
    fi
    _claude_copilot_unset_env
    # Subshell scopes CLAUDE_CODE_USE_VERTEX (and the re-exports below) to this
    # one invocation only — parent shell's env is untouched once claude exits.
    (
        export CLAUDE_CODE_USE_VERTEX=1
        export CLOUD_ML_REGION ANTHROPIC_VERTEX_PROJECT_ID
        [[ -n "$ANTHROPIC_VERTEX_BASE_URL" ]] && export ANTHROPIC_VERTEX_BASE_URL
        command claude "$@"
    )
}

# ---------------------------------------------------------------------------
# claude mode switching: `claude` dispatches to the raw claude binary through
# either Google Vertex AI (vertex, default) or the copilot-api gateway
# (copilot). Persisted in ~/.config/claude-mode so the choice survives
# across shells.

typeset -g _claude_mode_file="${XDG_CONFIG_HOME:-$HOME/.config}/claude-mode"

_claude_mode_get() {
    local mode=""
    [[ -r "$_claude_mode_file" ]] && IFS= read -r mode < "$_claude_mode_file"
    case "$mode" in
        copilot) print -r -- copilot ;;
        *)       print -r -- vertex ;;   # missing/unknown fails safe to vertex
    esac
}

claude-mode() {
    if (( $# > 1 )); then
        echo "Usage: claude-mode [copilot|vertex]" >&2
        return 1
    fi
    case "$1" in
        copilot|vertex)
            # >| overrides NO_CLOBBER; fail loudly if persistence fails
            if ! mkdir -p "${_claude_mode_file:h}" ||
               ! print -r -- "$1" >| "$_claude_mode_file"; then
                echo "❌ Failed to persist claude mode in ${_claude_mode_file}" >&2
                return 1
            fi
            echo "claude mode: $1"
            ;;
        "")
            echo "claude mode: $(_claude_mode_get)"
            echo "usage: claude-mode [copilot|vertex]"
            ;;
        *)
            echo "Usage: claude-mode [copilot|vertex]" >&2
            return 1
            ;;
    esac
}

# Guard for live shells still carrying an old claude→happy alias; `function`
# keyword form: the name is never alias-expanded (at parse time or under
# zcompile), so this definition is safe even if the guard misses.
unalias claude 2>/dev/null || true   # tolerate missing alias under ERR_EXIT
function claude {
    local mode="$(_claude_mode_get)"
    # stderr so piped/scripted output (e.g. claude -p) stays clean
    echo "claude mode: ${mode} (switch: claude-mode copilot|vertex)" >&2
    if [[ "$mode" == copilot ]]; then
        claude-copilot "$@"
    else
        claude-vertex "$@"
    fi
}
