# Run from the local origin/dev checkout, not the published (upstream) package.
# alias copilot-api="npx @jeffreycao/copilot-api@latest start --claude-code"   # upstream/published, disabled
alias copilot-api="NODE_USE_SYSTEM_CA=1 bun run --cwd \$HOME/git/copilot-api ./src/main.ts start --claude-code"

# Claude Code via GitHub Copilot (copilot-api gateway)
#
# claude-copilot replicates the env command generated by
# `copilot-api start --claude-code` (https://github.com/kaovilai/copilot-api),
# including two not-yet-merged fixes:
#   PR #1 (kaovilai/copilot-api#1): CLAUDE_CODE_USE_VERTEX=0 and
#       CLAUDE_CODE_USE_BEDROCK=0 so an environment already configured for
#       Vertex AI/Bedrock routes to the gateway instead of erroring 403.
#   PR #2 (kaovilai/copilot-api#2): latest available model auto-selected per
#       family; ANTHROPIC_MODEL defaults to Sonnet, falling back to Opus.
#       Of the per-tier ANTHROPIC_DEFAULT_{OPUS,SONNET,HAIKU}_MODEL exports
#       PR #2 generates, only Sonnet is kept here (pinned to the gateway's 1M
#       id); Opus/Haiku are unset so the CLI picks its own — see the block in
#       claude-copilot() below.
# The gateway server itself runs from the local ~/git/copilot-api checkout
# (origin/dev fork), not the published npm package — see the runner block in
# claude-copilot() below. Set COPILOT_API_DIR to point elsewhere, or unset/
# rmdir that path to fall back to the commented-out bunx/npx upstream lines.
#
# By default, claude-copilot sets DISABLE_NON_ESSENTIAL_MODEL_CALLS=1 and
# CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 to cut nonessential
# traffic/telemetry through the gateway. Tradeoff: this also disables Claude
# Code's Monitor tool (https://code.claude.com/docs/en/tools-reference#monitor-tool),
# which breaks anything relying on it (e.g. inter-session plugin's push-based
# messaging). Set CLAUDE_COPILOT_ENABLE_MONITOR=1 to opt back into Monitor
# (e.g. `CLAUDE_COPILOT_ENABLE_MONITOR=1 claude-copilot` or `cec`).
#
# Also defines claude-vertex (raw claude binary routed through Google Vertex
# AI, using CLOUD_ML_REGION/ANTHROPIC_VERTEX_PROJECT_ID already exported in
# the shell — same vars used by computer-use-claude/cecon elsewhere in this
# repo), claude-vertex-dashboard (opens that project's GCP console dashboard
# via the comet skill), claude-ollama (raw claude binary routed through a
# local Ollama server on :11434 for fully offline use, auto-selecting a
# gemma4 model per opus/sonnet/haiku tier, with a memory pre-flight check
# before loading each one — see claude-ollama-models to force a re-pick,
# ollama-serve-kill to stop the auto-started server), plus
# the mode-dispatching `claude` function and the `claude-mode` switcher
# (copilot ↔ vertex ↔ ollama, vertex is default) — see bottom of file.

# Highest-versioned Claude model for a family from /v1/models JSON.
# Mirrors PR #2's getLatestModelForFamily: numeric major-then-minor compare,
# handles claude-opus-4.8, claude-opus-4-5-20251101, claude-3-opus-... forms.
# Outputs .claude_model_id (falls back to .id) so the 1M-context variant
# (e.g. "claude-sonnet-5[1m]") is preferred over the plain default-context id
# when the gateway advertises one for that model.
_claude_copilot_latest_model() {
    local family="$1" models_json="$2"
    jq -r --arg fam "$family" '
        [(.data // [])[]
         | select(((.id? // empty) | strings) as $i
                  | ($i | test("claude"; "i")) and ($i | test($fam; "i")))]
        | map({out: (.claude_model_id? // .id),
               v: ((try (.id | capture("(?<maj>[0-9]+)(?:[.-](?<min>[0-9]+))?")) catch null) as $m
                   | if $m == null then 0
                     else (($m.maj | tonumber) * 1000) + (($m.min // "0") | tonumber)
                     end)})
        | sort_by(.v) | last // {} | .out // empty
    ' <<< "$models_json"
}

# Names only (no values) — used to clean up when switching to `vertex` mode
# so gateway config doesn't leak across.
typeset -ga _claude_copilot_env_names=(
    ANTHROPIC_BASE_URL
    ANTHROPIC_AUTH_TOKEN
    ANTHROPIC_MODEL
    ANTHROPIC_DEFAULT_OPUS_MODEL
    ANTHROPIC_DEFAULT_SONNET_MODEL
    ANTHROPIC_DEFAULT_HAIKU_MODEL
    CLAUDE_CODE_USE_VERTEX
    CLAUDE_CODE_USE_BEDROCK
    DISABLE_NON_ESSENTIAL_MODEL_CALLS
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
    CLAUDE_CODE_ATTRIBUTION_HEADER
    CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION
    CLAUDE_CODE_DISABLE_TERMINAL_TITLE
    CLAUDE_CODE_ENABLE_AWAY_SUMMARY
)

_claude_copilot_unset_env() {
    unset "${_claude_copilot_env_names[@]}"
}

claude-copilot() {
    if ! command -v jq &>/dev/null; then
        echo "❌ jq not found. Install it with: brew install jq" >&2
        return 1
    fi

    local port="${COPILOT_API_PORT:-4141}"
    local base="http://localhost:${port}"
    local log="${TMPDIR:-/tmp}/copilot-api-${port}.log"

    # Start the gateway if nothing is serving yet
    if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
        local -a runner
        local repo_dir="${COPILOT_API_DIR:-$HOME/git/copilot-api}"
        if [[ -d "$repo_dir/.git" ]] && command -v bun &>/dev/null; then
            # Local origin/dev checkout — bun runs the TS source directly, so
            # uncommitted work-in-progress fixes are picked up with no build step.
            runner=(env NODE_USE_SYSTEM_CA=1 bun run --cwd "$repo_dir" ./src/main.ts)
        elif command -v bunx &>/dev/null; then
            # upstream/published fallback, disabled by default (see above)
            # runner=(bunx copilot-api@latest)
            echo "❌ Local checkout not found at ${repo_dir}. Set COPILOT_API_DIR or uncomment the bunx/npx fallback." >&2
            return 1
        elif command -v npx &>/dev/null; then
            # runner=(npx -y copilot-api@latest)
            echo "❌ Local checkout not found at ${repo_dir}. Set COPILOT_API_DIR or uncomment the bunx/npx fallback." >&2
            return 1
        else
            echo "❌ Need bunx or npx to run copilot-api. Install bun or node." >&2
            return 1
        fi
        echo "Starting copilot-api on ${base} (log: ${log})..."
        ("${runner[@]}" start --port "${port}" >> "${log}" 2>&1 &)
        local i
        for i in {1..60}; do
            curl -sf --max-time 2 "${base}/v1/models" -o /dev/null && break
            sleep 1
        done
        if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
            echo "❌ copilot-api not ready on ${base} after 60s." >&2
            echo "   First run needs GitHub device auth: tail -f ${log}" >&2
            echo "   Or run interactively once: ${runner[*]} start --port ${port}" >&2
            return 1
        fi
    fi

    local models_json
    models_json=$(curl -sf --max-time 10 "${base}/v1/models") || {
        echo "❌ Failed to fetch ${base}/v1/models" >&2
        return 1
    }

    local opus sonnet haiku
    opus=$(_claude_copilot_latest_model opus "$models_json")
    sonnet=$(_claude_copilot_latest_model sonnet "$models_json")
    haiku=$(_claude_copilot_latest_model haiku "$models_json")

    local main_model="${sonnet:-$opus}"
    if [[ -z "$main_model" ]]; then
        echo "❌ No Claude models available from ${base}/v1/models" >&2
        return 1
    fi

    echo "claude-copilot → opus: ${opus:-n/a}, sonnet: ${sonnet:-n/a}, haiku: ${haiku:-n/a}"

    # Env block mirrors the --claude-code generated command + PR #1/#2 fixes.
    local -a envs
    envs=(
        ANTHROPIC_BASE_URL="${base}"
        ANTHROPIC_AUTH_TOKEN="dummy"
        ANTHROPIC_MODEL="${main_model}"
        CLAUDE_CODE_USE_VERTEX=0
        CLAUDE_CODE_USE_BEDROCK=0
        CLAUDE_CODE_ATTRIBUTION_HEADER=0
        CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION=false
        CLAUDE_CODE_DISABLE_TERMINAL_TITLE=true
        CLAUDE_CODE_ENABLE_AWAY_SUMMARY=0
    )
    if [[ -z "$CLAUDE_COPILOT_ENABLE_MONITOR" || "$CLAUDE_COPILOT_ENABLE_MONITOR" == 0 ]]; then
        envs+=(
            DISABLE_NON_ESSENTIAL_MODEL_CALLS=1
            CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
        )
    fi
    # Opus/Haiku tier defaults are deliberately NOT exported (diverging from
    # PR #2), so the CLI's own built-in defaults apply and stay current as
    # Claude Code ships newer models. They are unset rather than merely omitted
    # because the shell may already export them for Vertex (see secrets.zsh) —
    # a stale pin there would otherwise leak into gateway mode and pick an
    # older model than the gateway offers.
    unset ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
    # Sonnet is the exception: pin it to the gateway's detected id so the 1M-
    # context variant (claude-sonnet-5[1m]) is used rather than the CLI's
    # default-context Sonnet.
    if [[ -n "$sonnet" ]]; then
        envs+=(ANTHROPIC_DEFAULT_SONNET_MODEL="${sonnet}")
    else
        unset ANTHROPIC_DEFAULT_SONNET_MODEL
    fi

    # `export` writes into the calling shell (not a subprocess-only scope) so
    # any later child process — including Claude Code re-entering an agent
    # shell via the left-arrow session view — inherits the gateway config
    # instead of falling back to default subscription auth.
    # `command` bypasses the claude() shell function without exec'ing a new
    # process (unlike env), avoiding claude() → claude-copilot → claude()
    # recursion while keeping the exported vars in this same shell.
    export "${envs[@]}"
    command claude "$@"
}

# copilot-api-kill: stop the detached gateway process started by
# claude-copilot. There's no saved PID (it's launched via `(... &)` in a
# subshell), so this finds whatever's listening on COPILOT_API_PORT
# (default 4141) and kills it, escalating to SIGKILL if it won't die.
copilot-api-kill() {
    local port="${COPILOT_API_PORT:-4141}"
    local -a pids
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -z "${pids[1]}" ]]; then
        echo "No process listening on port ${port}."
        return 1
    fi
    echo "Killing copilot-api on port ${port} (pid: ${pids[*]})..."
    kill "${pids[@]}" 2>/dev/null
    sleep 1
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -n "${pids[1]}" ]]; then
        echo "Still alive, sending SIGKILL..."
        kill -9 "${pids[@]}" 2>/dev/null
    fi
}

# ---------------------------------------------------------------------------
# claude-vertex: raw claude binary, routed through Google Vertex AI. Unlike
# claude-copilot, no local gateway process is needed — Claude Code talks to
# Vertex directly once CLAUDE_CODE_USE_VERTEX is set. Requires
# CLOUD_ML_REGION and ANTHROPIC_VERTEX_PROJECT_ID already exported in the
# shell (same vars computer-use-claude/cecon/claude-container use elsewhere
# in this repo) and gcloud ADC set up (`gcloud auth application-default
# login`).
claude-vertex() {
    if [[ -z "$CLOUD_ML_REGION" || -z "$ANTHROPIC_VERTEX_PROJECT_ID" ]]; then
        echo "❌ CLOUD_ML_REGION and ANTHROPIC_VERTEX_PROJECT_ID must be exported to use Vertex AI." >&2
        return 1
    fi
    _claude_copilot_unset_env
    # Subshell scopes CLAUDE_CODE_USE_VERTEX (and the re-exports below) to this
    # one invocation only — parent shell's env is untouched once claude exits.
    (
        export CLAUDE_CODE_USE_VERTEX=1
        export CLOUD_ML_REGION ANTHROPIC_VERTEX_PROJECT_ID
        [[ -n "$ANTHROPIC_VERTEX_BASE_URL" ]] && export ANTHROPIC_VERTEX_BASE_URL
        command claude "$@"
    )
}

# ---------------------------------------------------------------------------
# claude-vertex-dashboard: open the Google Cloud console dashboard for the
# Vertex AI project Claude Code routes through (ANTHROPIC_VERTEX_PROJECT_ID —
# same var claude-vertex requires above), via the comet skill's opener script
# so it's a single call instead of manually building/opening the URL.
claude-vertex-dashboard() {
    if [[ -z "$ANTHROPIC_VERTEX_PROJECT_ID" ]]; then
        echo "❌ ANTHROPIC_VERTEX_PROJECT_ID must be exported to open its dashboard." >&2
        return 1
    fi
    local script="$HOME/.claude/skills/comet/scripts/comet.sh"
    if [[ ! -x "$script" ]]; then
        echo "❌ comet skill script not found or not executable at ${script}." >&2
        return 1
    fi
    "$script" "https://console.cloud.google.com/home/dashboard?project=${ANTHROPIC_VERTEX_PROJECT_ID}"
}

# ---------------------------------------------------------------------------
# claude-ollama: raw claude binary, routed through a local Ollama server
# (http://localhost:11434) so Claude Code can run fully offline against
# local models. Mirrors claude-copilot's shape — local HTTP server → same
# ANTHROPIC_BASE_URL/ANTHROPIC_AUTH_TOKEN/ANTHROPIC_DEFAULT_*_MODEL exports,
# same detached-subshell auto-start + poll-loop, same `export` (not a
# subshell) so descendant Claude Code sessions inherit the routing — but
# Ollama has no /v1/models-style family+version metadata to auto-rank, so
# each of the three model tiers (opus/sonnet/haiku) is resolved once via
# _claude_ollama_resolve_model and persisted to $_claude_ollama_models_file;
# see claude-ollama-models below to force a re-pick. ANTHROPIC_AUTH_TOKEN is
# a dummy value: Ollama's OpenAI-compatible endpoint doesn't check it, but
# Claude Code requires the env var to be non-empty.

typeset -g _claude_ollama_models_file="${XDG_CONFIG_HOME:-$HOME/.config}/claude-ollama-models"

# Hardcoded fallback model tag for a Claude Code tier, used only when
# _claude_ollama_resolve_model has no persisted choice AND gets no
# interactive answer. Override per-tier via env, e.g.
# CLAUDE_OLLAMA_HAIKU_MODEL=llama3.2:3b claude-ollama-models haiku.
#
# Defaults below are hardware-matched to this machine (Apple M4 Pro, 48GB
# unified memory, 14 cores), verified-real ollama.com tags as of Aug 2026:
#   haiku  -> gemma4:12b (~8GB Q4)  fast/cheap
#   sonnet -> gemma4:26b (~16GB Q4) default daily driver
#   opus   -> gemma4:31b (~20GB Q4) flagship, still leaves headroom in 48GB
# gemma4 ships same-family/different-size tags (e2b/e4b/12b/26b/31b), tagged
# tools+thinking, explicitly designed for "frontier-level performance at
# each size" — the closest available mirror of the opus/sonnet/haiku size
# ladder.
_claude_ollama_default_model() {
    case "$1" in
        opus)   print -r -- "${CLAUDE_OLLAMA_OPUS_MODEL:-gemma4:31b}" ;;
        sonnet) print -r -- "${CLAUDE_OLLAMA_SONNET_MODEL:-gemma4:26b}" ;;
        haiku)  print -r -- "${CLAUDE_OLLAMA_HAIKU_MODEL:-gemma4:12b}" ;;
        *)
            echo "❌ Unknown tier: $1 (expected opus, sonnet, or haiku)" >&2
            return 1
            ;;
    esac
}

# Estimate a model's memory footprint in bytes for the resource pre-flight
# check below.
#   $1 = tag, $2 = tags_json (from /api/tags, may be empty)
# Prefers the real on-disk size from tags_json (already pulled). Falls back
# to parsing a trailing parameter-count suffix like "31b"/"1.5b" from the
# tag name (matches our own gemma4 defaults and most Ollama naming
# conventions) at ~0.6 bytes/param, a rough figure for typical Q4_K_M
# quantization. Prints nothing and fails if neither source yields a number
# — callers must treat that as "can't estimate, skip the check" rather than
# guessing.
_claude_ollama_model_size_bytes() {
    local tag="$1" tags_json="$2"
    zmodload zsh/mathfunc 2>/dev/null   # for int() below
    if [[ -n "$tags_json" ]] && command -v jq &>/dev/null; then
        local size
        size=$(jq -r --arg n "$tag" '(.models // [])[] | select(.name == $n) | .size // empty' <<< "$tags_json" 2>/dev/null | head -1)
        if [[ -n "$size" && "$size" != "null" ]]; then
            print -r -- "$size"
            return 0
        fi
    fi
    local suffix="${tag##*:}"
    if [[ "$suffix" =~ '^([0-9]+(\.[0-9]+)?)[bB]$' ]]; then
        print -r -- $(( int(${match[1]} * 1000000000 * 0.6) ))
        return 0
    fi
    return 1
}

# Pre-flight resource gate: warn (and, when possible, ask) before loading a
# model this machine may not have the memory for, rather than finding out
# via a mid-session OOM/crash. Dotfiles travel across machines (see
# migrate-to-new-laptop) so this runs on every resolve, not just the first
# — a tier persisted from a 48GB machine could be wrong on a smaller one.
# Set CLAUDE_OLLAMA_SKIP_RESOURCE_CHECK=1 to bypass entirely.
#
#   $1 = tier, $2 = tag, $3 = tags_json, $4 = count of locally-pulled
#        models available as alternatives (0 disables the "pick a
#        different model" option — nothing to pick from yet)
#
# CPU core count is advisory only (affects speed, not whether a model can
# load at all) and never blocks.
#
# Returns: 0 = proceed, 1 = abort, 2 = caller should re-resolve this tier
# (interactive "pick a different model" choice) — see the recursive
# `_claude_ollama_resolve_model "$tier" force` call sites below.
_claude_ollama_check_resources() {
    local tier="$1" tag="$2" tags_json="$3" alternatives="${4:-0}"
    [[ -n "$CLAUDE_OLLAMA_SKIP_RESOURCE_CHECK" ]] && return 0

    local total_mem cores
    if [[ "$(uname)" == "Darwin" ]]; then
        total_mem=$(sysctl -n hw.memsize 2>/dev/null)
        cores=$(sysctl -n hw.ncpu 2>/dev/null)
    elif [[ -r /proc/meminfo ]]; then
        total_mem=$(awk '/^MemTotal:/ { print $2 * 1024; exit }' /proc/meminfo 2>/dev/null)
        cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
    fi
    [[ -z "$total_mem" ]] && return 0   # can't check -> don't block

    if [[ -n "$cores" ]] && (( cores > 0 && cores < 4 )); then
        echo "⚠️  Only ${cores} CPU cores available — local inference will be slow." >&2
    fi

    local size_bytes
    size_bytes=$(_claude_ollama_model_size_bytes "$tag" "$tags_json") || return 0  # can't estimate -> don't block

    # 1.5x on-disk size for context/runtime overhead vs. a 75%-of-total
    # safety budget (leaves headroom for the OS, Claude Code itself, and
    # everything else running) — both rough rules of thumb, not exact.
    local needed budget needed_gb total_gb
    needed=$(( size_bytes * 3 / 2 ))
    budget=$(( total_mem * 3 / 4 ))
    (( needed <= budget )) && return 0

    needed_gb=$(( needed / 1073741824 ))
    total_gb=$(( total_mem / 1073741824 ))
    echo "⚠️  '${tag}' (${tier} tier) needs an estimated ${needed_gb}GB; this machine has ${total_gb}GB total." >&2

    if [[ -t 0 ]]; then
        local -a opts=("Proceed anyway" "Abort")
        (( alternatives > 0 )) && opts=("Proceed anyway" "Pick a different model for '${tier}'" "Abort")
        local pick
        if command -v fzf &>/dev/null; then
            pick=$(print -l -- "${opts[@]}" | fzf --height 40% --reverse --header "Not enough memory for '${tag}' — what now?")
        else
            echo "Not enough memory for '${tag}' — what now?" >&2
            select pick in "${opts[@]}"; do
                [[ -n "$pick" ]] && break
            done
        fi
        case "$pick" in
            "Proceed anyway")   echo "Proceeding anyway — may be slow or fail to load." >&2; return 0 ;;
            "Pick a different model for '${tier}'") return 2 ;;
            *)                  echo "Aborted." >&2; return 1 ;;
        esac
    else
        echo "❌ Refusing to proceed non-interactively. Pick a smaller model: claude-ollama-models ${tier}" >&2
        echo "   Or override: CLAUDE_OLLAMA_SKIP_RESOURCE_CHECK=1" >&2
        return 1
    fi
}

# Ensure a local Ollama server is reachable, auto-starting one if not.
# Shared by claude-ollama() and _claude_ollama_resolve_model() (so
# claude-ollama-models also works standalone, without claude-ollama having
# run first). Mirrors claude-copilot's detached-subshell + up-to-60s
# poll-loop pattern exactly, including the log-file-under-TMPDIR idiom.
_claude_ollama_ensure_server() {
    local base="http://localhost:11434"
    local log="${TMPDIR:-/tmp}/ollama-serve.log"

    curl -sf --max-time 2 "${base}/api/tags" -o /dev/null && return 0

    if ! command -v ollama &>/dev/null; then
        echo "❌ ollama not found. Install it with: brew install ollama" >&2
        return 1
    fi

    echo "Starting ollama serve on ${base} (log: ${log})..." >&2
    # This function's stdout is captured via $(...) by every caller (either
    # directly, or transitively — _claude_ollama_resolve_model, which calls
    # this, is itself captured in claude-ollama()), so anything not sent to
    # stderr here corrupts the resolved model tag those callers parse.
    #
    # OLLAMA_CONTEXT_LENGTH only takes effect for a server WE start here —
    # Ollama docs recommend 64k+ for larger repos; default below is
    # overridable, but if a server is already running (started outside our
    # control) we have no way to change its context length short of
    # restarting it, which isn't attempted.
    (OLLAMA_CONTEXT_LENGTH="${CLAUDE_OLLAMA_CONTEXT_LENGTH:-65536}" ollama serve >> "${log}" 2>&1 &)
    # Wall-clock deadline, not an iteration count: each curl can itself take
    # up to --max-time (2s), so 60 iterations of curl+sleep could overrun the
    # "after 60s" message below by up to 2x in the worst case. `local
    # SECONDS=0` localizes zsh's elapsed-seconds special var to this
    # function's scope.
    local SECONDS=0
    while (( SECONDS < 60 )); do
        curl -sf --max-time 2 "${base}/api/tags" -o /dev/null && return 0
        sleep 1
    done
    echo "❌ ollama serve not ready on ${base} after 60s." >&2
    echo "   Check the log: tail -f ${log}" >&2
    echo "   Or run interactively once: ollama serve" >&2
    return 1
}

# Resolve (and persist) the Ollama model tag for one Claude Code tier.
#   $1 = tier: opus | sonnet | haiku
#   $2 = "force" to bypass the persisted choice and re-prompt/re-autopick
# Resolution order:
#   1. Already persisted in $_claude_ollama_models_file (skipped if $2==force)
#   2. Interactive pick from locally-pulled models: fzf, else `select` builtin
#   3. Autopick _claude_ollama_default_model's tag for that tier, `ollama
#      pull`-ing it if not already present locally — reached whenever there's
#      no interactive answer (non-interactive shell, fzf/select unavailable,
#      empty selection, or Ctrl+C), so this never hangs on a prompt nothing
#      is there to answer.
# Every candidate tag is checked via _claude_ollama_check_resources before
# it's persisted/pulled; a "pick a different model" response recurses into
# this same function with force set, re-entering the interactive picker.
# Prints the resolved tag on stdout; persists it as TIER=model in
# $_claude_ollama_models_file. Returns 1 (nothing printed) on hard failure.
_claude_ollama_resolve_model() {
    local tier="$1" force="$2"
    local base="http://localhost:11434"

    local default
    default=$(_claude_ollama_default_model "$tier") || return 1

    _claude_ollama_ensure_server || return 1

    local -a local_models
    local tags_json
    tags_json=$(curl -sf --max-time 5 "${base}/api/tags" 2>/dev/null)
    if [[ -n "$tags_json" ]] && command -v jq &>/dev/null; then
        local_models=("${(@f)$(jq -r '.models[].name' <<< "$tags_json" 2>/dev/null)}")
        # zsh quirk: splitting genuinely-empty command substitution output
        # (e.g. .models is []) via ${(@f)...} yields a 1-element array
        # holding one empty string, not a 0-length array — this filters
        # that back out so an empty local store doesn't falsely look like
        # one pullable "alternative" to _claude_ollama_check_resources or
        # the interactive picker below.
        local_models=("${(@)local_models:#}")
    fi

    if [[ -z "$force" && -r "$_claude_ollama_models_file" ]]; then
        local existing
        existing=$(awk -F= -v t="${(U)tier}" '$1 == t {print $2; exit}' "$_claude_ollama_models_file" 2>/dev/null)
        if [[ -n "$existing" ]]; then
            _claude_ollama_check_resources "$tier" "$existing" "$tags_json" "${#local_models[@]}"
            case $? in
                0)
                    # The persisted tag may no longer be pulled (e.g. `ollama
                    # rm`'d, or pruned for space) since it was recorded —
                    # (Ie) is the same exact-match index-lookup used above,
                    # 0 means absent. Re-pull the exact persisted tag rather
                    # than silently falling through to re-pick, since the
                    # user's prior choice is still what they asked for, just
                    # missing locally.
                    if (( ${local_models[(Ie)$existing]} == 0 )); then
                        echo "Persisted ${tier} model '${existing}' is no longer pulled locally — re-pulling..." >&2
                        if ! ollama pull "$existing"; then
                            echo "❌ 'ollama pull ${existing}' failed. Check your connection, or pick a different model: claude-ollama-models ${tier}" >&2
                            return 1
                        fi
                    fi
                    print -r -- "$existing"
                    return 0
                    ;;
                2) _claude_ollama_resolve_model "$tier" force; return $? ;;
                *) return 1 ;;
            esac
        fi
    fi

    local chosen=""
    # -t 0: stdin is a tty. fzf reopens /dev/tty internally for keypresses
    # regardless of this process's own stdin, so it won't fail fast on a
    # redirected/non-interactive stdin the way most commands do — it just
    # hangs waiting on a keypress that will never come. Gating on -t 0 here
    # is what makes the "no interactive answer" -> autopick fallback (see
    # function comment above) actually reachable from a non-interactive
    # shell/script instead of hanging.
    if [[ -t 0 && ${#local_models[@]} -gt 0 ]]; then
        if command -v fzf &>/dev/null; then
            chosen=$(print -l -- "${local_models[@]}" \
                | fzf --height 40% --reverse \
                      --header "Select an Ollama model for the '${tier}' tier (Ctrl+C to autopick ${default})")
        else
            echo "Select an Ollama model for the '${tier}' tier (Ctrl+C to autopick ${default}):" >&2
            select chosen in "${local_models[@]}"; do
                [[ -n "$chosen" ]] && break
            done
        fi
    fi

    if [[ -n "$chosen" ]]; then
        _claude_ollama_check_resources "$tier" "$chosen" "$tags_json" "${#local_models[@]}"
        case $? in
            0) ;;
            2) _claude_ollama_resolve_model "$tier" force; return $? ;;
            *) return 1 ;;
        esac
    else
        chosen="$default"
        echo "No selection for '${tier}' tier — autopicking ${chosen}." >&2
        # (Ie) = exact-match index lookup (0 if absent) — avoids treating
        # $chosen as a glob pattern (a tag could contain glob-special chars)
        # and, unlike the array-slice-based ${(M)arr:#pat} filter, actually
        # works without also requiring the array (@) flag.
        local not_yet_pulled=$(( ${local_models[(Ie)$chosen]} == 0 ))
        _claude_ollama_check_resources "$tier" "$chosen" "$tags_json" "${#local_models[@]}"
        case $? in
            0) ;;
            2) _claude_ollama_resolve_model "$tier" force; return $? ;;
            *) return 1 ;;
        esac
        if (( not_yet_pulled )); then
            echo "Pulling ${chosen} (first run only; needs internet access, can take several minutes for larger tags)..." >&2
            if ! ollama pull "$chosen"; then
                echo "❌ 'ollama pull ${chosen}' failed. Check your connection and retry, or pick an already-pulled tag via: claude-ollama-models ${tier}" >&2
                return 1
            fi
        fi
    fi

    # Sequential per-tier resolution (opus, then sonnet, then haiku — see
    # claude-ollama below) means each rewrite of the persistence file sees
    # the previous tier's write already on disk; no concurrent writers, so
    # no lock/race handling is needed here.
    mkdir -p "${_claude_ollama_models_file:h}"
    local -a kept=()
    [[ -r "$_claude_ollama_models_file" ]] && kept=("${(f)$(grep -v "^${(U)tier}=" "$_claude_ollama_models_file")}")
    # Same empty-array quirk as local_models above: if grep -v matched
    # nothing (e.g. this is the first tier ever persisted), kept would
    # otherwise be a 1-element array holding an empty string, writing a
    # spurious blank line ahead of the real TIER=model line.
    kept=("${(@)kept:#}")
    { [[ ${#kept[@]} -gt 0 ]] && print -l -- "${kept[@]}"; print -r -- "${(U)tier}=${chosen}"; } >| "$_claude_ollama_models_file"
    print -r -- "$chosen"
}

claude-ollama() {
    _claude_ollama_ensure_server || return 1

    local opus sonnet haiku
    opus=$(_claude_ollama_resolve_model opus) || return 1
    sonnet=$(_claude_ollama_resolve_model sonnet) || return 1
    haiku=$(_claude_ollama_resolve_model haiku) || return 1

    echo "claude-ollama → opus: ${opus}, sonnet: ${sonnet}, haiku: ${haiku}"

    # Scrub any stale gateway/Vertex config before routing to Ollama — reuses
    # claude-vertex's helper/array rather than adding a new one:
    # _claude_copilot_env_names already names every var Ollama also sets
    # (ANTHROPIC_BASE_URL/AUTH_TOKEN/MODEL/DEFAULT_*_MODEL,
    # CLAUDE_CODE_USE_VERTEX/BEDROCK), so this alone is enough to make
    # switching in from any other mode leak-free.
    _claude_copilot_unset_env

    # Unlike claude-copilot (which leaves Opus/Haiku unset so the CLI's own
    # built-in default applies), all three tiers are pinned unconditionally
    # below: the CLI's built-in defaults are Anthropic-hosted model names
    # that don't exist on a local Ollama server, so every tier needs an
    # explicit, locally-pulled tag or Claude Code has nothing valid to
    # request. CLAUDE_CODE_USE_VERTEX/BEDROCK aren't re-set here (unlike
    # claude-copilot's envs block) — _claude_copilot_unset_env just above
    # already unset them, and claude-copilot only sets them explicitly
    # because it does NOT call that unset helper first.
    local -a envs
    envs=(
        ANTHROPIC_BASE_URL="http://localhost:11434"
        ANTHROPIC_AUTH_TOKEN="ollama"
        ANTHROPIC_MODEL="${sonnet}"
        ANTHROPIC_DEFAULT_OPUS_MODEL="${opus}"
        ANTHROPIC_DEFAULT_SONNET_MODEL="${sonnet}"
        ANTHROPIC_DEFAULT_HAIKU_MODEL="${haiku}"
    )

    # `export` (not a subshell) so descendant Claude Code sessions — e.g. an
    # agent sub-shell re-entering `claude` — inherit the Ollama routing, same
    # rationale as claude-copilot above: this is also a local-server backend.
    # `command` bypasses the claude() dispatcher without exec'ing a new
    # process, avoiding claude() -> claude-ollama -> claude() recursion.
    export "${envs[@]}"
    command claude "$@"
}

# ollama-serve-kill: stop the detached `ollama serve` process started by
# claude-ollama. Mirrors copilot-api-kill above — no saved PID (launched via
# `(... &)` in a subshell), so this finds whatever's listening on 11434 and
# kills it, escalating to SIGKILL if it won't die.
ollama-serve-kill() {
    local port=11434
    local -a pids
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -z "${pids[1]}" ]]; then
        echo "No process listening on port ${port}."
        return 1
    fi
    echo "Killing ollama serve on port ${port} (pid: ${pids[*]})..."
    kill "${pids[@]}" 2>/dev/null
    sleep 1
    pids=("${(f)$(lsof -ti "tcp:${port}" 2>/dev/null)}")
    if [[ -n "${pids[1]}" ]]; then
        echo "Still alive, sending SIGKILL..."
        kill -9 "${pids[@]}" 2>/dev/null
    fi
}

# claude-ollama-models: force re-selection of one (or all) model tiers used
# by claude-ollama, bypassing the persisted choice in
# $_claude_ollama_models_file. Structurally mirrors claude-mode's
# arg-count-validated case-statement shape (below), though semantically the
# no-arg case here re-resolves all three tiers rather than merely printing
# the current ones — claude-mode's no-arg prints without changing anything.
claude-ollama-models() {
    if (( $# > 1 )); then
        echo "Usage: claude-ollama-models [opus|sonnet|haiku]" >&2
        return 1
    fi
    local -a tiers
    case "$1" in
        opus|sonnet|haiku) tiers=("$1") ;;
        "")                tiers=(opus sonnet haiku) ;;
        *)
            echo "Usage: claude-ollama-models [opus|sonnet|haiku]" >&2
            return 1
            ;;
    esac
    local tier chosen
    for tier in "${tiers[@]}"; do
        chosen=$(_claude_ollama_resolve_model "$tier" force) || return 1
        echo "${tier}: ${chosen}"
    done
}

# ---------------------------------------------------------------------------
# claude mode switching: `claude` dispatches to the raw claude binary through
# Google Vertex AI (vertex, default), the copilot-api gateway (copilot), or a
# local Ollama server (ollama). Persisted in ~/.config/claude-mode so the
# choice survives across shells.

typeset -g _claude_mode_file="${XDG_CONFIG_HOME:-$HOME/.config}/claude-mode"

_claude_mode_get() {
    local mode=""
    [[ -r "$_claude_mode_file" ]] && IFS= read -r mode < "$_claude_mode_file"
    case "$mode" in
        copilot) print -r -- copilot ;;
        ollama)  print -r -- ollama ;;
        *)       print -r -- vertex ;;   # missing/unknown fails safe to vertex
    esac
}

claude-mode() {
    if (( $# > 1 )); then
        echo "Usage: claude-mode [copilot|vertex|ollama]" >&2
        return 1
    fi
    case "$1" in
        copilot|vertex|ollama)
            # >| overrides NO_CLOBBER; fail loudly if persistence fails
            if ! mkdir -p "${_claude_mode_file:h}" ||
               ! print -r -- "$1" >| "$_claude_mode_file"; then
                echo "❌ Failed to persist claude mode in ${_claude_mode_file}" >&2
                return 1
            fi
            echo "claude mode: $1"
            ;;
        "")
            echo "claude mode: $(_claude_mode_get)"
            echo "usage: claude-mode [copilot|vertex|ollama]"
            ;;
        *)
            echo "Usage: claude-mode [copilot|vertex|ollama]" >&2
            return 1
            ;;
    esac
}

# Guard for live shells still carrying an old claude→happy alias; `function`
# keyword form: the name is never alias-expanded (at parse time or under
# zcompile), so this definition is safe even if the guard misses.
unalias claude 2>/dev/null || true   # tolerate missing alias under ERR_EXIT
function claude {
    local mode="$(_claude_mode_get)"
    # stderr so piped/scripted output (e.g. claude -p) stays clean
    echo "claude mode: ${mode} (switch: claude-mode copilot|vertex|ollama)" >&2
    case "$mode" in
        copilot) claude-copilot "$@" ;;
        ollama)  claude-ollama "$@" ;;
        *)       claude-vertex "$@" ;;
    esac
}
