# Claude Code via GitHub Copilot (copilot-api gateway)
#
# claude-copilot replicates the env command generated by
# `copilot-api start --claude-code` (https://github.com/kaovilai/copilot-api),
# including two not-yet-merged fixes:
#   PR #1 (kaovilai/copilot-api#1): CLAUDE_CODE_USE_VERTEX=0 and
#       CLAUDE_CODE_USE_BEDROCK=0 so an environment already configured for
#       Vertex AI/Bedrock routes to the gateway instead of erroring 403.
#   PR #2 (kaovilai/copilot-api#2): latest available model auto-selected per
#       family and exported as ANTHROPIC_DEFAULT_{OPUS,SONNET,HAIKU}_MODEL;
#       ANTHROPIC_MODEL defaults to Sonnet, falling back to Opus; tiers with
#       no available model are omitted.
# The gateway server itself runs from the published copilot-api package — the
# PR fixes only affect the generated launch command, which is inlined here.
#
# Also defines the mode-dispatching `claude` function and the `claude-mode`
# switcher (copilot ↔ default/happy) — see bottom of file.

# Highest-versioned Claude model for a family from /v1/models JSON.
# Mirrors PR #2's getLatestModelForFamily: numeric major-then-minor compare,
# handles claude-opus-4.8, claude-opus-4-5-20251101, claude-3-opus-... forms.
_claude_copilot_latest_model() {
    local family="$1" models_json="$2"
    jq -r --arg fam "$family" '
        [(.data // [])[] | .id? // empty | strings
         | select(test("claude"; "i") and test($fam; "i"))]
        | map({id: .,
               v: ((try (capture("(?<maj>[0-9]+)(?:[.-](?<min>[0-9]+))?")) catch null) as $m
                   | if $m == null then 0
                     else (($m.maj | tonumber) * 1000) + (($m.min // "0") | tonumber)
                     end)})
        | sort_by(.v) | last // {} | .id // empty
    ' <<< "$models_json"
}

claude-copilot() {
    if ! command -v jq &>/dev/null; then
        echo "❌ jq not found. Install it with: brew install jq" >&2
        return 1
    fi

    local port="${COPILOT_API_PORT:-4141}"
    local base="http://localhost:${port}"
    local log="${TMPDIR:-/tmp}/copilot-api-${port}.log"

    # Start the gateway if nothing is serving yet
    if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
        local -a runner
        if command -v bunx &>/dev/null; then
            runner=(bunx copilot-api@latest)
        elif command -v npx &>/dev/null; then
            runner=(npx -y copilot-api@latest)
        else
            echo "❌ Need bunx or npx to run copilot-api. Install bun or node." >&2
            return 1
        fi
        echo "Starting copilot-api on ${base} (log: ${log})..."
        ("${runner[@]}" start --port "${port}" >> "${log}" 2>&1 &)
        local i
        for i in {1..60}; do
            curl -sf --max-time 2 "${base}/v1/models" -o /dev/null && break
            sleep 1
        done
        if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
            echo "❌ copilot-api not ready on ${base} after 60s." >&2
            echo "   First run needs GitHub device auth: tail -f ${log}" >&2
            echo "   Or run interactively once: ${runner[*]} start --port ${port}" >&2
            return 1
        fi
    fi

    local models_json
    models_json=$(curl -sf --max-time 10 "${base}/v1/models") || {
        echo "❌ Failed to fetch ${base}/v1/models" >&2
        return 1
    }

    local opus sonnet haiku
    opus=$(_claude_copilot_latest_model opus "$models_json")
    sonnet=$(_claude_copilot_latest_model sonnet "$models_json")
    haiku=$(_claude_copilot_latest_model haiku "$models_json")

    local main_model="${sonnet:-$opus}"
    if [[ -z "$main_model" ]]; then
        echo "❌ No Claude models available from ${base}/v1/models" >&2
        return 1
    fi

    echo "claude-copilot → opus: ${opus:-n/a}, sonnet: ${sonnet:-n/a}, haiku: ${haiku:-n/a}"

    # Env block mirrors the --claude-code generated command + PR #1/#2 fixes.
    local -a envs
    envs=(
        ANTHROPIC_BASE_URL="${base}"
        ANTHROPIC_AUTH_TOKEN="dummy"
        ANTHROPIC_MODEL="${main_model}"
        CLAUDE_CODE_USE_VERTEX=0
        CLAUDE_CODE_USE_BEDROCK=0
        DISABLE_NON_ESSENTIAL_MODEL_CALLS=1
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
        CLAUDE_CODE_ATTRIBUTION_HEADER=0
        CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION=false
        CLAUDE_CODE_DISABLE_TERMINAL_TITLE=true
        CLAUDE_CODE_ENABLE_AWAY_SUMMARY=0
    )
    [[ -n "$opus" ]] && envs+=(ANTHROPIC_DEFAULT_OPUS_MODEL="${opus}")
    [[ -n "$sonnet" ]] && envs+=(ANTHROPIC_DEFAULT_SONNET_MODEL="${sonnet}")
    [[ -n "$haiku" ]] && envs+=(ANTHROPIC_DEFAULT_HAIKU_MODEL="${haiku}")

    # env(1) bypasses the claude shell function (functions are invisible to
    # env; it execs the claude binary from PATH). Never replace with a bare
    # `claude` call — claude() → claude-copilot → claude() would recurse.
    env "${envs[@]}" claude "$@"
}

# ---------------------------------------------------------------------------
# claude mode switching: `claude` dispatches to happy (default) or the raw
# claude binary through the copilot-api gateway (copilot). Persisted in
# ~/.config/claude-mode so the choice survives across shells.

typeset -g _claude_mode_file="${XDG_CONFIG_HOME:-$HOME/.config}/claude-mode"

_claude_mode_get() {
    local mode=""
    [[ -r "$_claude_mode_file" ]] && IFS= read -r mode < "$_claude_mode_file"
    case "$mode" in
        copilot) print -r -- copilot ;;
        *)       print -r -- default ;;   # missing/unknown fails safe
    esac
}

claude-mode() {
    if (( $# > 1 )); then
        echo "Usage: claude-mode [copilot|default]" >&2
        return 1
    fi
    case "$1" in
        copilot|default)
            # >| overrides NO_CLOBBER; fail loudly if persistence fails
            if ! mkdir -p "${_claude_mode_file:h}" ||
               ! print -r -- "$1" >| "$_claude_mode_file"; then
                echo "❌ Failed to persist claude mode in ${_claude_mode_file}" >&2
                return 1
            fi
            echo "claude mode: $1"
            ;;
        "")
            echo "claude mode: $(_claude_mode_get)"
            echo "usage: claude-mode [copilot|default]"
            ;;
        *)
            echo "Usage: claude-mode [copilot|default]" >&2
            return 1
            ;;
    esac
}

# Guard for live shells still carrying the old claude→happy alias; `function`
# keyword form: the name is never alias-expanded (at parse time or under
# zcompile), so this definition is safe even if the guard misses.
unalias claude 2>/dev/null || true   # tolerate missing alias under ERR_EXIT
function claude {
    local mode="$(_claude_mode_get)"
    # stderr so piped/scripted output (e.g. claude -p) stays clean
    echo "claude mode: ${mode} (switch: claude-mode copilot|default)" >&2
    if [[ "$mode" == copilot ]]; then
        claude-copilot "$@"          # raw claude binary; NO happy-only flags
    else
        happy --enable-auto-mode --permission-mode auto "$@"
    fi
}
