alias gofmtgitdiff='git diff --name-only  | xargs -L 1 go fmt'
alias gofmtgitdiffmain='git diff upstream/main --name-only | grep .go$  | xargs -L 1 go fmt'
alias gofmtgitdiffmaster='git diff upstream/master --name-only | grep .go$  | xargs -L 1 go fmt'
alias grf='golangci-lint run --fix'
alias grfw='while ! golangci-lint run --fix 2>&1 | grep -v "parallel golangci-lint is running"; do echo "Waiting for golangci-lint to be available..."; sleep 1; done'
