znap function create-ocp-aws() {
    # Core implementation for AWS OpenShift cluster creation
    # Parameters:
    #   $1 - Command/option (help, gather, delete, no-delete)
    #   $2 - Architecture (arm64 or amd64)
    
    # Use specified openshift-install or default to 4.19.0-ec.4
    local OPENSHIFT_INSTALL=${OPENSHIFT_INSTALL:-openshift-install-4.19.0-ec.4}
    local ARCHITECTURE=$2
    local ARCH_SUFFIX=${2}
    $OPENSHIFT_INSTALL version
    # Check if help is requested
    if [[ $1 == "help" ]]; then
        echo "Usage: create-ocp-aws-$ARCH_SUFFIX [OPTION]"
        echo "Create an OpenShift cluster on AWS using $ARCHITECTURE architecture"
        echo ""
        echo "Options:"
        echo "  help      Display this help message"
        echo "  gather    Gather bootstrap logs from the installation directory"
        echo "  delete    Just delete the cluster without recreating it"
        echo "  no-delete Skip deletion of existing cluster before creation"
        echo ""
        echo "Prerequisites:"
        echo "  - AWS_REGION environment variable (defaults to us-east-1 if not set)"
        echo "  - AWS_BASEDOMAIN environment variable (defaults to mg.dog8code.com if not set)"
        echo "  - AWS credentials must be configured"
        echo "  - SSH key must be added to the agent (ssh-add ~/.ssh/id_rsa)"
        echo "  - Pull secret must exist at ~/pull-secret.txt"
        echo ""
        echo "Directory:"
        echo "  Installation files will be created in: $OCP_MANIFESTS_DIR/$TODAY-aws-$ARCH_SUFFIX"
        echo ""
        echo "Note:"
        echo "  When creating clusters alongside existing ones (option 3), a unique"
        echo "  name will be generated by adding a suffix (e.g., -1, -2) to avoid conflicts"
        return 0
    fi
    
    # Set default values for AWS_REGION and AWS_BASEDOMAIN if not already set
    if [[ -z "$AWS_REGION" ]]; then
        echo "INFO: AWS_REGION not set, defaulting to us-east-1"
        AWS_REGION="us-east-1"
    fi
    
    if [[ -z "$AWS_BASEDOMAIN" ]]; then
        echo "INFO: AWS_BASEDOMAIN not set, defaulting to mg.dog8code.com"
        AWS_BASEDOMAIN="mg.dog8code.com"
    fi
    
    # Verify that the requested architecture is supported by the installer
    if ! $OPENSHIFT_INSTALL version | grep -q "release architecture $ARCHITECTURE"; then
        echo "WARN: $ARCHITECTURE architecture not supported in current release payload"
        echo "WARN: To use $ARCHITECTURE, you need an openshift-install binary built for $ARCHITECTURE"
        echo "WARN: Run 'openshift-install version' to check if 'release architecture $ARCHITECTURE' is present"
        return 1
    else
        echo "INFO: Using $ARCHITECTURE architecture for cluster nodes (supported by current release payload)"
    fi
    
    OCP_CREATE_DIR=$OCP_MANIFESTS_DIR/$TODAY-aws-$ARCH_SUFFIX
    CLUSTER_BASE_NAME=tkaovila-$TODAY-$ARCH_SUFFIX
    CLUSTER_NAME=$CLUSTER_BASE_NAME #max 21 char allowed
    
    # Check if we need to modify the cluster name to avoid conflicts
    # This happens when option 3 (proceed alongside existing) was selected
    if [[ -n "$PROCEED_WITH_EXISTING_CLUSTERS" && "$PROCEED_WITH_EXISTING_CLUSTERS" == "true" ]]; then
        # Look for existing clusters with the same base name
        local suffix_num=1
        # Search for existing directories with similar names
        while find "$OCP_MANIFESTS_DIR" -type d -name "*${CLUSTER_BASE_NAME}*" 2>/dev/null | grep -q .; do
            # Try appending increasing numbers until we find a unique name
            CLUSTER_NAME="${CLUSTER_BASE_NAME}-${suffix_num}"
            echo "Found existing cluster with similar name, trying: $CLUSTER_NAME"
            # Check if the new name exists
            if ! find "$OCP_MANIFESTS_DIR" -type d -name "*${CLUSTER_NAME}*" 2>/dev/null | grep -q .; then
                # Found a unique name
                OCP_CREATE_DIR=$OCP_MANIFESTS_DIR/$TODAY-aws-$ARCH_SUFFIX-$suffix_num
                echo "Using unique cluster name: $CLUSTER_NAME and directory: $OCP_CREATE_DIR"
                break
            fi
            ((suffix_num++))
            # Safety check to avoid infinite loop
            if [[ $suffix_num -gt 10 ]]; then
                echo "ERROR: Cannot find a unique cluster name after 10 attempts"
                return 1
            fi
        done
    fi
    
    if [[ $1 == "gather" ]]; then
        $OPENSHIFT_INSTALL gather bootstrap --dir $OCP_CREATE_DIR || return 1
        return 0
    fi
    
    if [[ $1 != "no-delete" ]]; then
        $OPENSHIFT_INSTALL destroy cluster --dir $OCP_CREATE_DIR || echo "no existing cluster"
        $OPENSHIFT_INSTALL destroy bootstrap --dir $OCP_CREATE_DIR || echo "no existing bootstrap"
        ((rm -r $OCP_CREATE_DIR && echo "removed existing create dir") || (true && echo "no existing install dir")) || return 1
    fi
    
    # if param is delete then stop here
    if [[ $1 == "delete" ]]; then
        return 0
    fi
    
    # Check for existing clusters before proceeding
    check-for-existing-clusters "aws" "$ARCH_SUFFIX" || return 1
    
    mkdir -p $OCP_CREATE_DIR && \
    echo "additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: $AWS_BASEDOMAIN
compute:
- architecture: $ARCHITECTURE
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: $ARCHITECTURE
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: $CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: $AWS_REGION
publish: External
pullSecret: '$(cat ~/pull-secret.txt)'
sshKey: |
  $(cat ~/.ssh/id_rsa.pub)
" > $OCP_CREATE_DIR/install-config.yaml && echo "created install-config.yaml" || return 1
    
    $OPENSHIFT_INSTALL create manifests --dir $OCP_CREATE_DIR || return 1
    # Set the appropriate release image based on architecture
    if [[ "$ARCHITECTURE" == "arm64" ]]; then
        RELEASE_IMAGE=$OCP_FUNCTIONS_RELEASE_IMAGE_ARM64
    else
        RELEASE_IMAGE=$OCP_FUNCTIONS_RELEASE_IMAGE_AMD64
    fi
    
    # Use the architecture-specific release image
    echo "INFO: Using architecture-specific release image for $ARCHITECTURE: $RELEASE_IMAGE"
    # Export the release image override
    export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=$RELEASE_IMAGE
    echo "INFO: Exported OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=$RELEASE_IMAGE"
    
    # Create the cluster
    $OPENSHIFT_INSTALL create cluster --dir $OCP_CREATE_DIR \
        --log-level=info || $OPENSHIFT_INSTALL gather bootstrap --dir $OCP_CREATE_DIR || return 1
    
    # Unset the release image override after use
    echo "INFO: Unsetting OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE"
    unset OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE
        
    # Reset the flag to avoid affecting future cluster creations
    if [[ -n "$PROCEED_WITH_EXISTING_CLUSTERS" ]]; then
        unset PROCEED_WITH_EXISTING_CLUSTERS
    fi
}

znap function create-ocp-aws-arm64() {
    # ARM64 wrapper function
    create-ocp-aws "$1" "arm64"
}

znap function create-ocp-aws-amd64() {
    # AMD64 wrapper function
    create-ocp-aws "$1" "amd64"
}
