# ---------------------------------------------------------------------------
# claude-copilot: Claude Code via GitHub Copilot (copilot-api gateway)
#
# claude-copilot replicates the env command generated by
# `copilot-api start --claude-code` (https://github.com/kaovilai/copilot-api),
# including two not-yet-merged fixes:
#   PR #1 (kaovilai/copilot-api#1): CLAUDE_CODE_USE_VERTEX=0 and
#       CLAUDE_CODE_USE_BEDROCK=0 so an environment already configured for
#       Vertex AI/Bedrock routes to the gateway instead of erroring 403.
#   PR #2 (kaovilai/copilot-api#2): latest available model auto-selected per
#       family; ANTHROPIC_MODEL defaults to Sonnet, falling back to Opus.
#       All three per-tier ANTHROPIC_DEFAULT_{OPUS,SONNET,HAIKU}_MODEL
#       exports PR #2 generates are kept here, each pinned to the gateway's
#       detected id (its 1M-context variant when one's offered) — see the
#       block in claude-copilot() below.
# The gateway server itself runs from the local ~/git/copilot-api checkout
# (origin/dev fork), not the published npm package — see the runner block in
# claude-copilot() below. Set COPILOT_API_DIR to point elsewhere, or unset/
# rmdir that path to fall back to the commented-out bunx/npx upstream lines.

# Run from the local origin/dev checkout, not the published (upstream) package.
# alias copilot-api="npx @jeffreycao/copilot-api@latest start --claude-code"   # upstream/published, disabled
alias copilot-api="NODE_USE_SYSTEM_CA=1 bun run --cwd \$HOME/git/copilot-api ./src/main.ts start --claude-code"

claude-copilot() {
    if ! command -v jq &>/dev/null; then
        echo "❌ jq not found. Install it with: $(_claude_pkg_install_hint jq)" >&2
        return 1
    fi

    local port="${COPILOT_API_PORT:-4141}"
    local base="http://localhost:${port}"
    local log="${TMPDIR:-/tmp}/copilot-api-${port}.log"

    # Hot reload -- see _claude_proxy_sync. copilot-api reads its GitHub OAuth
    # token (github_token) and config.json only at start, so a re-login or
    # config edit restarts the gateway. A running gateway with no recorded
    # fingerprint is adopted.
    local capi_data="${COPILOT_API_HOME:-$HOME/.local/share/copilot-api}"
    local cfp
    cfp=$(_claude_proxy_fp "$(_claude_file_hash "${capi_data}/github_token" "${capi_data}/config.json")" "$port")
    _claude_proxy_sync claude-copilot copilot-api "${base}/v1/models" "$cfp" claude-copilot-kill 1 || return 1

    # Start the gateway if nothing is serving yet
    if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
        local -a runner
        local repo_dir="${COPILOT_API_DIR:-$HOME/git/copilot-api}"
        local have_checkout=0 have_bun=0
        [[ -d "$repo_dir/.git" ]] && have_checkout=1
        command -v bun &>/dev/null && have_bun=1
        if (( have_checkout && have_bun )); then
            # Local origin/dev checkout — bun runs the TS source directly, so
            # uncommitted work-in-progress fixes are picked up with no build step.
            runner=(env NODE_USE_SYSTEM_CA=1 bun run --cwd "$repo_dir" ./src/main.ts)
        elif (( ! have_checkout )); then
            echo "❌ No local checkout at ${repo_dir} (git clone -b dev https://github.com/kaovilai/copilot-api ${repo_dir}), or set COPILOT_API_DIR to point elsewhere." >&2
            return 1
        elif (( ! have_bun )); then
            echo "❌ bun not found. Install it with: $(_claude_pkg_install_hint bun 'curl -fsSL https://bun.sh/install | bash')" >&2
            echo "   (upstream/published bunx/npx fallback is disabled by default -- see the comments above this function)" >&2
            return 1
        fi
        echo "Starting copilot-api on ${base} (log: ${log})..." >&2
        _claude_proxy_start "$log" "${runner[@]}" start --port "${port}" || return 1
        local i
        for i in {1..60}; do
            curl -sf --max-time 2 "${base}/v1/models" -o /dev/null && break
            sleep 1
        done
        if ! curl -sf --max-time 2 "${base}/v1/models" -o /dev/null; then
            echo "❌ copilot-api not ready on ${base} after 60s." >&2
            echo "   First run needs GitHub device auth: tail -f ${log}" >&2
            echo "   Or run interactively once: ${runner[*]} start --port ${port}" >&2
            return 1
        fi
        # re-hash after start: the gateway may rewrite config.json itself
        cfp=$(_claude_proxy_fp "$(_claude_file_hash "${capi_data}/github_token" "${capi_data}/config.json")" "$port")
        _claude_proxy_record copilot-api "$cfp"
    fi

    local models_json
    models_json=$(curl -sf --max-time 10 "${base}/v1/models") || {
        echo "❌ Failed to fetch ${base}/v1/models" >&2
        return 1
    }

    local opus sonnet haiku fable
    opus=$(_claude_copilot_latest_model opus "$models_json")
    sonnet=$(_claude_copilot_latest_model sonnet "$models_json")
    haiku=$(_claude_copilot_latest_model haiku "$models_json")
    fable=$(_claude_copilot_latest_model fable "$models_json")

    local main_model="${sonnet:-$opus}"
    if [[ -z "$main_model" ]]; then
        echo "❌ No Claude models available from ${base}/v1/models" >&2
        return 1
    fi

    echo "claude-copilot → opus: ${opus:-n/a}, sonnet: ${sonnet:-n/a}, haiku: ${haiku:-n/a}, fable: ${fable:-n/a}" >&2

    # Env block mirrors the --claude-code generated command + PR #1/#2 fixes.
    local -a envs
    envs=(
        ANTHROPIC_BASE_URL="${base}"
        ANTHROPIC_AUTH_TOKEN="dummy"
        ANTHROPIC_MODEL="${main_model}"
        CLAUDE_CODE_USE_VERTEX=0
        CLAUDE_CODE_USE_BEDROCK=0
        CLAUDE_CODE_ATTRIBUTION_HEADER=0
        CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION=false
        CLAUDE_CODE_DISABLE_TERMINAL_TITLE=true
        CLAUDE_CODE_ENABLE_AWAY_SUMMARY=0
        # SDK disables tool search by default for any non-first-party
        # ANTHROPIC_BASE_URL (this local gateway included) since most
        # proxies don't forward tool_reference blocks / the enabling beta
        # header. Verified this gateway's local origin/dev checkout does
        # NOT strip it: allowedAnthropicBetas in
        # src/services/copilot/create-messages.ts already allows
        # advanced-tool-use-2025-11-20, which per Anthropic's own
        # 2025-11-24 blog is the single beta flag Tool Search Tool /
        # Programmatic Tool Calling / tool_reference all share (confirmed
        # live via a 5-test suite added to that checkout — see
        # tests/create-messages.test.ts there). Safe to force back on.
        ENABLE_TOOL_SEARCH=true
    )
    # All three tiers are pinned to the gateway's detected id (via
    # _claude_copilot_latest_model, which always finds whichever version is
    # currently latest — no hardcoded version number to go stale) so each
    # tier's [1m]-suffixed variant is used when the gateway offers one,
    # rather than the CLI's own built-in default falling back to a
    # default-context id when a tier isn't pinned. Previously Opus/Haiku
    # were deliberately left unpinned (diverging from PR #2) specifically
    # so the CLI's built-in default would "stay current" -- but
    # _claude_copilot_latest_model already re-resolves the latest version
    # on every claude-copilot call, so pinning it stays just as current
    # while also actually getting the 1M-context variant when available
    # (verified: the gateway currently offers claude-opus-5[1m], but an
    # unpinned Opus tier was silently using the CLI's plain 200K default
    # instead). Still unset first, not merely omitted, in case the shell
    # already exports these for Vertex (see secrets.zsh) -- a stale pin
    # there would otherwise leak into gateway mode.
    unset ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_FABLE_MODEL
    [[ -n "$opus" ]]   && envs+=(ANTHROPIC_DEFAULT_OPUS_MODEL="${opus}")
    [[ -n "$sonnet" ]] && envs+=(ANTHROPIC_DEFAULT_SONNET_MODEL="${sonnet}")
    [[ -n "$haiku" ]]  && envs+=(ANTHROPIC_DEFAULT_HAIKU_MODEL="${haiku}")
    [[ -n "$fable" ]]  && envs+=(ANTHROPIC_DEFAULT_FABLE_MODEL="${fable}")

    # `export` writes into the calling shell (not a subprocess-only scope) so
    # any later child process — including Claude Code re-entering an agent
    # shell via the left-arrow session view — inherits the gateway config
    # instead of falling back to default subscription auth.
    # `command` bypasses the claude() shell function without exec'ing a new
    # process (unlike env), avoiding claude() → claude-copilot → claude()
    # recursion while keeping the exported vars in this same shell.
    export "${envs[@]}"
    # Gateway display names (e.g. "Claude Opus 4.8") for pinned tiers and extras
    local -a picker_extras
    picker_extras=(${(f)"$(print -r -- "$models_json" | jq -r '.data[] | select(.id | test("embedding"; "i") | not) | "\(.id)|\(.display_name // .name // "")"' 2>/dev/null | _claude_picker_extras)"})
    local _t _id _suffix
    local -a picker_pins
    for _t in opus sonnet haiku fable; do
        _id="${(P)_t}"
        [[ -z "$_id" ]] && continue
        picker_pins+=("${_t}=${_id}|$(print -r -- "$models_json" | jq -r --arg id "${_id%\[*}" '[.data[] | select(.id == $id)][0] | (.display_name // .name // "")' 2>/dev/null)")
    done
    _claude_picker_args "${picker_pins[@]}" "${picker_extras[@]}"
    _claude_invoke "${reply[@]}" "$@"
}

# claude-copilot-kill: stop a stale/unresponsive detached copilot-api gateway
# process holding COPILOT_API_PORT (default 4141), so claude-copilot's own
# startup check (curl .../v1/models) can spawn a fresh one instead of
# treating the dead-but-still-listening process as "already running". No
# saved PID (it's launched via `(... &)` in a subshell), so this finds
# whatever's listening on the port and kills it, escalating to SIGKILL if it
# won't die.
claude-copilot-kill() {
    local port="${COPILOT_API_PORT:-4141}"
    local -a pids
    # -sTCP:LISTEN: without it, lsof also matches processes with an
    # established connection TO this port -- which includes the very Claude
    # Code session routing through the gateway (and our own in-flight curl
    # health-checks), so an unfiltered kill takes them down too. Same guard
    # claude-ollama-kill uses too.
    pids=("${(f)$(lsof -ti "tcp:${port}" -sTCP:LISTEN 2>/dev/null)}")
    if [[ -z "${pids[1]}" ]]; then
        echo "No process listening on port ${port}."
        return 1
    fi
    echo "Killing copilot-api on port ${port} (pid: ${pids[*]})..."
    kill "${pids[@]}" 2>/dev/null
    sleep 1
    pids=("${(f)$(lsof -ti "tcp:${port}" -sTCP:LISTEN 2>/dev/null)}")
    if [[ -n "${pids[1]}" ]]; then
        echo "Still alive, sending SIGKILL..."
        kill -9 "${pids[@]}" 2>/dev/null
    fi
}

# copilot-api-details: print base URL + API key for each local gateway
# (copilot-api, claude-vertex proxy), e.g. for pointing the Claude Desktop
# app at one -- same values claude-copilot()/claude-vertex() export as
# ANTHROPIC_BASE_URL/ANTHROPIC_AUTH_TOKEN, just surfaced without starting a
# claude session. Flags each gateway RUNNING/not running via its own
# liveliness check, but always prints the URL/key it WOULD use either way.
copilot-api-details() {
    local capi_port="${COPILOT_API_PORT:-4141}"
    local capi_base="http://localhost:${capi_port}"
    local capi_status="not running"
    curl -sf --max-time 2 "${capi_base}/v1/models" -o /dev/null && capi_status="running"

    local cvp_port="${CLAUDE_VERTEX_PROXY_PORT:-4142}"
    local cvp_base="http://127.0.0.1:${cvp_port}"
    local cvp_key="${CLAUDE_VERTEX_PROXY_TOKEN:-vertex-proxy-local}"
    local cvp_status="not running"
    curl -sf --max-time 2 "${cvp_base}/health/liveliness" -o /dev/null && cvp_status="running"

    echo "copilot-api gateway (${capi_status}):"
    echo "  Base URL: ${capi_base}"
    echo "  API Key:  dummy"
    echo "claude-vertex proxy (${cvp_status}):"
    echo "  Base URL: ${cvp_base}"
    echo "  API Key:  ${cvp_key}"
}

# Pre-rename names -- claude-copilot-kill is the current name.
alias kill-copilot-api='claude-copilot-kill'
alias copilot-api-kill='claude-copilot-kill'
